### ISSUE TITLE
Comment on aggregate notes

### ISSUE THREAD

**Issue by jburse** [dtonhofer/prolog_notes#1]
To implement limit for aggregates, in SWI-Prolog you can 
combine it with limit/2 from library(solution_sequences)).

Could be what somebody was looking for here:

**LogicalCaptain said (2020-04-22T15:51:56):**
"aggregate" needs a "limit" option whereby you can select up to "Limit" results ...
[https://www.swi-prolog.org/pldoc/man?section=aggregate](https://www.swi-prolog.org/pldoc/man?section=aggregate)

limit/2 and offset/2 from library(solution_sequences)) are lightweight,
they do not materialize results. Just an clever application of call_nth/2.

**Comment by dtonhofer** [comment]
Thanks! I will look into it.

**Comment by dtonhofer** [comment]
This issue was opened in April. I can't believe it. What happened to time? I will close it.
