### ISSUE TITLE
between/4

### ISSUE THREAD

**Issue by jburse** [dtonhofer/prolog_notes#2]
I am expecting this to fail, but it succeeds:

```
?- between(5,-5,-2,13).
true.
?- between(5,-5,2,13).
true.
```
I was just looking what it enumerates, and whether 13 is among:

```
?- between(5,-5,-2,X).
X = 5 ;
X = 3 ;
X = 1 ;
X = -1 ;
X = -3 ;
X = -5.
?- between(5,-5,2,X).
false.
```
No 13 among.

**Comment by dtonhofer** [comment]
Thank you for testing! 

You are right, that comes from not being exhaustive in tests (AND forgetting the bounds check). Gotta fix that.

**Comment by dtonhofer** [comment]
Oh God I found another error that passed all the unit tests ... due to the fact that I wrote
guard, !, if -> then ; else. 
instead of
guard, !, (if -> then ; else). 
with ; having the highest priority the control flow is going places.

But since I have the unit tests, easily fixed.

**Comment by dtonhofer** [comment]
Fixed! Thanks again.

```
?- between(5,-5,-2,13).
false.

?- between(5,-5,2,13).
false.
```

Also:

```
|    rt(_).
% PL-Unit: between_with_step ................................................................................ done
% All 80 tests passed
```

"keeps the bar green to keep the code clean"  (within limits)
